Stimfit: CFileIO Class Reference
CFileIO Class Reference
#include <FileIO.hpp>
Public Member Functions
CFileIO ()
CFileIO (FILEHANDLE hFile)
CFileIO (HANDLE hFile)
~CFileIO ()
BOOL Create (LPCTSTR szFileName, BOOL bReadOnly, DWORD dwAttributes=FILE_ATTRIBUTE_NORMAL)
BOOL CreateEx (LPCTSTR szFileName, DWORD dwDesiredAccess, DWORD dwShareMode, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes)
BOOL Close ()
BOOL Read (void *pvBuffer, DWORD dwSizeInBytes, DWORD *pdwBytesRead=NULL)
BOOL Seek (LONGLONG lOffset, UINT uFlag=FILE_BEGIN, LONGLONG *plNewOffset=NULL)
LONGLONG GetFileSize ()
void SetFileHandle (FILEHANDLE hFile)
FILEHANDLE GetFileHandle () const
LPCTSTR GetFileName () const
FILEHANDLE Release ()
BOOL SetLastError ()
BOOL SetLastError (DWORD nError)
DWORD GetLastError () const
Detailed Description
Definition at line 22 of file FileIO.hpp.
Constructor & Destructor Documentation
CFileIO() [1/3]
CFileIO::CFileIO ()
CFileIO() [2/3]
CFileIO::CFileIO (FILEHANDLE hFile)
CFileIO() [3/3]
CFileIO::CFileIO (HANDLE hFile)
~CFileIO()
CFileIO::~CFileIO ()
Member Function Documentation
Close()
BOOL CFileIO::Close ()
Create()
BOOL CFileIO::Create (LPCTSTR szFileName, BOOL bReadOnly, DWORD dwAttributes = FILE_ATTRIBUTE_NORMAL)
CreateEx()
BOOL CFileIO::CreateEx (LPCTSTR szFileName, DWORD dwDesiredAccess, DWORD dwShareMode, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes)
GetFileHandle()
FILEHANDLE CFileIO::GetFileHandle () const inline
Definition at line 94 of file FileIO.hpp.
Referenced by CFileDescriptor::GetFileHandle().
GetFileName()
LPCTSTR CFileIO::GetFileName () const inline
Definition at line 84 of file FileIO.hpp.
GetFileSize()
LONGLONG CFileIO::GetFileSize ()
Referenced by CFileDescriptor::GetFileSize().
GetLastError()
DWORD CFileIO::GetLastError () const
Read()
BOOL CFileIO::Read (void * pvBuffer, DWORD dwSizeInBytes, DWORD * pdwBytesRead = NULL)
Referenced by CFileDescriptor::Read().
Release()
FILEHANDLE CFileIO::Release ()
Seek()
BOOL CFileIO::Seek (LONGLONG lOffset, UINT uFlag = FILE_BEGIN, LONGLONG * plNewOffset = NULL)
Referenced by CFileDescriptor::Seek().
SetFileHandle()
void CFileIO::SetFileHandle (FILEHANDLE hFile)
SetLastError() [1/2]
BOOL CFileIO::SetLastError ()
SetLastError() [2/2]
BOOL CFileIO::SetLastError (DWORD nError)
The documentation for this class was generated from the following file:
src/libstfio/abf/axon/Common/FileIO.hpp