Stimfit: CFileDescriptor Class Reference
CFileDescriptor Class Reference
#include <filedesc.hpp>
Public Member Functions
CFileDescriptor ()
~CFileDescriptor ()
void SetFlag (UINT uFlag)
BOOL TestFlag (UINT uFlag)
BOOL IsOK ()
BOOL Open (LPCTSTR szFileName, BOOL bReadOnly)
BOOL Read (void *pvBuffer, UINT uSizeInBytes)
BOOL Seek (LONGLONG llOffset, UINT uFlag, LONGLONG *pllOffset=NULL)
LONGLONG GetFileSize ()
BOOL CheckEpisodeNumber (UINT uEpisode)
void SetAcquiredEpisodes (UINT uEpisodes)
UINT GetAcquiredEpisodes () const
void SetAcquiredSamples (UINT uSamples)
BOOL AllocReadBuffer (UINT uBytes)
void FreeReadBuffer ()
void * GetReadBuffer ()
void SetCachedEpisode (UINT uEpisode, UINT uEpisodeSize)
UINT GetCachedEpisode () const
UINT GetCachedEpisodeSize () const
void SetLastEpiSize (UINT uEpiSize)
UINT GetLastEpiSize () const
BOOL PutSynchEntry (UINT uStart, UINT uLength, UINT uOffset=0)
BOOL GetSynchEntry (UINT uEpisode, Synch *pSynch)
UINT EpisodeLength (UINT uEpisode)
UINT GetSynchCount () const
void SetSynchMode (CSynch::eMODE eMode)
void ChangeSynchArray (CSynch *pNewSynch)
FILEHANDLE GetFileHandle ()
void SetOverlappedFlag (BOOL bOverlapped)
BOOL GetOverlappedFlag () const
BOOL SetLastError (int nError)
int GetLastError () const
Detailed Description
Definition at line 30 of file filedesc.hpp.
Constructor & Destructor Documentation
CFileDescriptor()
CFileDescriptor::CFileDescriptor ()
~CFileDescriptor()
CFileDescriptor::~CFileDescriptor ()
Member Function Documentation
AllocReadBuffer()
BOOL CFileDescriptor::AllocReadBuffer (UINT uBytes)
ChangeSynchArray()
void CFileDescriptor::ChangeSynchArray (CSynch * pNewSynch)
CheckEpisodeNumber()
BOOL CFileDescriptor::CheckEpisodeNumber (UINT uEpisode)
EpisodeLength()
UINT CFileDescriptor::EpisodeLength (UINT uEpisode)
FreeReadBuffer()
void CFileDescriptor::FreeReadBuffer ()
GetAcquiredEpisodes()
UINT CFileDescriptor::GetAcquiredEpisodes () const
GetCachedEpisode()
UINT CFileDescriptor::GetCachedEpisode () const
GetCachedEpisodeSize()
UINT CFileDescriptor::GetCachedEpisodeSize () const
GetFileHandle()
FILEHANDLE CFileDescriptor::GetFileHandle () inline
Definition at line 161 of file filedesc.hpp.
References CFileIO::GetFileHandle().
GetFileSize()
LONGLONG CFileDescriptor::GetFileSize () inline
Definition at line 183 of file filedesc.hpp.
References CFileIO::GetFileSize().
GetLastEpiSize()
UINT CFileDescriptor::GetLastEpiSize () const
GetLastError()
int CFileDescriptor::GetLastError () const
GetOverlappedFlag()
BOOL CFileDescriptor::GetOverlappedFlag () const
GetReadBuffer()
void * CFileDescriptor::GetReadBuffer () inline
Definition at line 246 of file filedesc.hpp.
GetSynchCount()
UINT CFileDescriptor::GetSynchCount () const
GetSynchEntry()
BOOL CFileDescriptor::GetSynchEntry (UINT uEpisode, Synch * pSynch) inline
Definition at line 235 of file filedesc.hpp.
References CSynch::Get().
IsOK()
BOOL CFileDescriptor::IsOK () inline
Definition at line 204 of file filedesc.hpp.
Open()
BOOL CFileDescriptor::Open (LPCTSTR szFileName, BOOL bReadOnly)
PutSynchEntry()
BOOL CFileDescriptor::PutSynchEntry (UINT uStart, UINT uLength, UINT uOffset = 0) inline
Definition at line 214 of file filedesc.hpp.
References CSynch::Put().
Read()
BOOL CFileDescriptor::Read (void * pvBuffer, UINT uSizeInBytes) inline
Definition at line 194 of file filedesc.hpp.
References ABF_EREADDATA, CFileIO::Read(), SetLastError(), and TRUE.
Seek()
BOOL CFileDescriptor::Seek (LONGLONG llOffset, UINT uFlag, LONGLONG * pllOffset = NULL) inline
Definition at line 172 of file filedesc.hpp.
References CFileIO::Seek().
SetAcquiredEpisodes()
void CFileDescriptor::SetAcquiredEpisodes (UINT uEpisodes)
SetAcquiredSamples()
void CFileDescriptor::SetAcquiredSamples (UINT uSamples)
SetCachedEpisode()
void CFileDescriptor::SetCachedEpisode (UINT uEpisode, UINT uEpisodeSize)
SetFlag()
void CFileDescriptor::SetFlag (UINT uFlag)
SetLastEpiSize()
void CFileDescriptor::SetLastEpiSize (UINT uEpiSize)
SetLastError()
BOOL CFileDescriptor::SetLastError (int nError)
Referenced by Read().
SetOverlappedFlag()
void CFileDescriptor::SetOverlappedFlag (BOOL bOverlapped)
SetSynchMode()
void CFileDescriptor::SetSynchMode (CSynch::eMODE eMode)
TestFlag()
BOOL CFileDescriptor::TestFlag (UINT uFlag)
The documentation for this class was generated from the following file:
src/libstfio/abf/axon/AxAbfFio32/filedesc.hpp