stimfit: Recording Class Reference
Recording Class Reference
Generic stimfit classes and functions
Represents the data within a file.
#include <recording.h>
Public Member Functions
Recording ()
Default constuctor.
Recording (const Channel &c_Channel)
Constructor.
Recording (const std::vector< Channel > &ChannelList)
Constructor.
Recording (std::size_t c_n_channels, std::size_t c_n_sections=0, std::size_t c_n_points=0)
Constructor.
virtual ~Recording ()
Destructor.
std::size_t GetChannelSize (std::size_t n_channel) const
Retrieves the number of sections in a channel.
const std::vector< Channel > & get () const
Retrieves the channels (read-only).
std::vector< Channel > & get ()
Retrieves the channels (read and write).
const std::string & GetFileDescription () const
Retrieves the file description.
const std::string & GetGlobalSectionDescription () const
Retrieves the common section description.
const std::string & GetScaling () const
Retrieves the scaling as a string.
const std::string & GetTime () const
Retrieves the time of recording as a string.
const std::string & GetDate () const
Retrieves the date of recording as a string.
const std::string & GetComment () const
Retrieves a comment string.
const std::string & GetXUnits () const
Retrieves the x units.
std::size_t size () const
Retrieves the size of the channel array.
double GetXScale () const
Retrieves the x scaling (sampling interval).
double GetSR () const
Retrieves the sampling rate (1 / x-scale)
const Channel & at (std::size_t n_c) const
Range-checked access to a channel (read-only).
Channel & at (std::size_t n_c)
Range-checked access to a channel (read and write).
std::size_t GetCurCh () const
Retrieves the index of the current channel.
std::size_t GetSecCh () const
Retrieves the index of the second channel.
std::size_t GetCurSec () const
Retrieves the index of the current section.
std::size_t GetMeasCursor () const
Retrieves the position of the measurement cursor (crosshair).
std::size_t GetBaseBeg () const
Retrieves the position of the left baseline cursor.
std::size_t GetBaseEnd () const
Retrieves the position of the right baseline cursor.
std::size_t GetPeakBeg () const
Retrieves the position of the left peak cursor.
std::size_t GetPeakEnd () const
Retrieves the position of the right peak cursor.
std::size_t GetFitBeg () const
Retrieves the position of the left fitting cursor.
std::size_t GetFitEnd () const
Retrieves the position of the right fitting cursor.
int GetPM () const
Retrieves the number of points used for averaging during peak calculation.
double GetLatencyBeg () const
Retrieves the position of the left latency cursor.
double GetLatencyEnd () const
Retrieves the position of the right latency cursor.
double GetLatency () const
Retrieves the latency.
double GetT20Real () const
Retrieves the time point at which 20% of the maximal amplitude have been reached.
double GetT80Real () const
Retrieves the time point at which 80% of the maximal amplitude have been reached.
double GetT50LeftReal () const
Retrieves the time point at which 50% of the maximal amplitude have been reached from the left of the peak.
double GetT50RightReal () const
Retrieves the time point at which 50% of the maximal amplitude have been reached from the right of the peak.
double GetT50Y () const
Retrieves the y value at 50% of the maximal amplitude.
double GetMaxRise () const
Retrieves the maximal slope of the rising phase.
double GetMaxDecay () const
Retrieves the maximal slope of the decaying phase.
double GetAPMaxRiseT () const
Retrieves the time point of the maximal slope of the rising phase in the second channel.
double GetAPMaxT () const
Retrieves the time point of the peak in the second channel.
double GetAPT50LeftReal () const
Retrieves the time point at which 50% of the max. amplitude have been reached from the left of the peak in the inactive channel.
double GetMaxRiseT () const
Retrieves the time point of the maximal slope during the rising phase.
double GetMaxRiseY () const
Retrieves the y-value at the time point of the maximal slope during the rising phase.
double GetMaxDecayT () const
Retrieves the time point of the maximal slope during the decaying phase.
double GetMaxDecayY () const
Retrieves the y-value at the time point of the maximal slope during the decaying phase.
double GetMeasValue ()
Retrieves the y-value at the measurement cursor (crosshair). Will update measCursor if out of range.
double GetPeak () const
Retrieves the peak value.
double GetBase () const
Retrieves the baseline.
double GetAPBase () const
Retrieves the baseline in the second channel.
double GetBaseSD () const
Retrieves the standard deviation of the baseline.
double GetThreshold () const
Retrieves the value at which the threshold slope is crossed.
double GetMaxT () const
Retrieves the time point at which the peak is found.
double GetThrT () const
Retrieves the time point at which the threshold slope is crossed.
double GetRT2080 () const
Retrieves the 20 to 80% rise time.
double GetHalfDuration () const
Retrieves the full width at half-maximal amplitude ("half duration").
double GetSlopeRatio () const
Retrieves ratio of the maximal slopes during the rising and decaying phase.
double GetPSlope () const
Retrieves the value of the Slope.
stf::latency_mode GetLatencyStartMode () const
Retrieves the mode of the latency start cursor.
stf::latency_mode GetLatencyEndMode () const
Retrieves the mode of the latency end cursor.
stf::latency_window_mode GetLatencyWindowMode () const
Retrieves the mode of the latency window.
stf::direction GetDirection () const
Retrieves the direction of peak calculations.
bool GetFromBase () const
Indicates whether to use the baseline as a reference for AP kinetics.
bool GetViewCrosshair () const
Indicates whether the measurement cursor (crosshair) value should be shown in the results table.
bool GetViewBaseline () const
Indicates whether the baseline value should be shown in the results table.
bool GetViewBaseSD () const
Indicates whether the baseline's standard deviation should be shown in the results table.
bool GetViewThreshold () const
Indicates whether the threshold should be shown in the results table.
bool GetViewPeakZero () const
Indicates whether the peak value (measured from zero) should be shown in the results table.
bool GetViewPeakBase () const
Indicates whether the peak value (measured from baseline) should be shown in the results table.
bool GetViewPeakThreshold () const
Indicates whether the peak value (measured from threshold) should be shown in the results table.
bool GetViewRT2080 () const
Indicates whether the 20 to 80% rise time should be shown in the results table.
bool GetViewT50 () const
Indicates whether the half duration should be shown in the results table.
bool GetViewRD () const
Indicates whether the ratio of the maximal slopes during rise and decay should be shown in the results table.
bool GetViewSlopeRise () const
Indicates whether the maximal slope during the rising phase should be shown in the results table.
bool GetViewSlopeDecay () const
Indicates whether the maximal slope during the decaying phase should be shown in the results table.
bool GetViewLatency () const
Indicates whether the latency should be shown in the results table.
bool GetViewCursors () const
Indicates whether two additional rows showing the positions of start and end cursors should be shown in the results table.
double GetSlopeForThreshold () const
Returns the slope for threshold detection.
const std::vector< std::size_t > & GetSelectedSections () const
Retrieves the indices of the selected sections (read-only).
std::vector< std::size_t > & GetSelectedSectionsW ()
Retrieves the indices of the selected sections (read and write).
const Vector_double & GetSelectBase () const
Retrieves the stored baseline values of the selected sections (read-only).
Vector_double & GetSelectBaseW ()
Retrieves the stored baseline values of the selected sections (read and write).
const Section & cur () const
Retrieves the currently accessed section in the active channel (read-only)
Section & cur ()
Retrieves the currently accessed section in the active channel (read and write)
const Section & sec () const
Retrieves the currently accessed section in the second (inactive) channel (read-only)
void SetFileDescription (const std::string &value)
Sets the file description.
void SetGlobalSectionDescription (const std::string &value)
Sets the common section description.
void SetScaling (const std::string &value)
Sets the scaling as a string.
void SetTime (const std::string &value)
Sets the time of recording as a string.
void SetDate (const std::string &value)
Sets the date of recording as a string.
void SetComment (const std::string &value)
Sets a comment string.
void SetGlobalYUnits (std::size_t n_channel, const std::string &value)
Sets the y units for a channel.
void SetXUnits (const std::string &value)
Sets the x units.
void SetXScale (double value)
Sets the x scaling.
void SetCurCh (std::size_t value)
Sets the index of the current channel.
void SetSecCh (std::size_t value)
Sets the index of the second channel.
void SetCurSec (std::size_t value)
Sets the index of the current section.
void SelectTrace (std::size_t sectionToSelect)
Selects a section.
bool UnselectTrace (std::size_t sectionToUnselect)
Unselects a section if it was selected before.
void SetMeasCursor (int value)
Sets the position of the measurement cursor (crosshair).
void SetBaseBeg (int value)
Sets the position of the left baseline cursor.
void SetBaseEnd (int value)
Sets the position of the right baseline cursor.
void SetPeakBeg (int value)
Sets the position of the left peak cursor.
void SetPeakEnd (int value)
Sets the position of the right peak cursor.
void SetFitBeg (int value)
Sets the position of the left fitting cursor.
void SetFitEnd (int value)
Sets the position of the right fitting cursor.
void SetLatencyBeg (double value)
Sets the position of the left latency cursor.
void SetLatencyEnd (double value)
Sets the position of the right latency cursor.
void SetLatency (double value)
Sets the latency.
void SetPM (int value)
Sets the number of points used for averaging during peak calculation.
void SetLatencyStartMode (stf::latency_mode value)
Sets the mode of the latency start cursor.
void SetLatencyEndMode (stf::latency_mode value)
Sets the mode of the latency end cursor.
void SetLatencyWindowMode (stf::latency_window_mode value)
Sets the mode of the latency end cursor.
void SetLatencyStartMode (int value)
Sets the mode of the latency start cursor.
void SetLatencyEndMode (int value)
Sets the mode of the latency end cursor.
void SetLatencyWindowMode (int value)
Sets the mode of the latency end cursor.
void SetDirection (stf::direction value)
Sets the direction of peak calculations.
void SetFromBase (bool frombase)
Sets the reference for AP kinetics measurements.
void SetViewCrosshair (bool value)
Determines whether the measurement cursor (crosshair) value should be shown in the results table.
void SetViewBaseline (bool value)
Determines whether the baseline value should be shown in the results table.
void SetViewBaseSD (bool value)
Determines whether the baseline's standard deviation should be shown in the results table.
void SetViewThreshold (bool value)
Determines whether the threshold should be shown in the results table.
void SetViewPeakZero (bool value)
Determines whether the peak value (measured from zero) should be shown in the results table.
void SetViewPeakBase (bool value)
Determines whether the peak value (measured from baseline) should be shown in the results table.
void SetViewPeakThreshold (bool value)
Determines whether the peak value (measured from threshold) should be shown in the results table.
void SetViewRT2080 (bool value)
Determines whether the 20 to 80% rise time should be shown in the results table.
void SetViewT50 (bool value)
Determines whether the half duration should be shown in the results table.
void SetViewRD (bool value)
Determines whether the ratio of the maximal slopes during rise and decay should be shown in the results table.
void SetViewSlopeRise (bool value)
Determines whether the maximal slope during the rising phase should be shown in the results table.
void SetViewSlopeDecay (bool value)
Determines whether the maximal slope during the decaying phase should be shown in the results table.
void SetViewLatency (bool value)
Determines whether the latency should be shown in the results table.
void SetViewCursors (bool value)
Determines whether two additional rows showing the positions of start and end cursors should be shown in the results table.
void SetSlopeForThreshold (double value)
Sets the slope where the baseline should be set.
void resize (std::size_t c_n_channels)
Resize the Recording to a new number of channels.
void InsertChannel (Channel &c_Channel, std::size_t pos)
Insert a Channel at a given position.
void CopyAttributes (const Recording &c_Recording)
Copy descriptive attributes from another Recording to this Recording.
void CopyCursors (const Recording &c_Recording)
Copies the cursor positions from another Recording to this Recording.
void Measure ()
Measure everything using functions defined in measlib.h.
void MakeAverage (Section &AverageReturn, Section &SigReturn, std::size_t channel, const std::vector< std::size_t > &section_index, bool isSig, const std::vector< int > &shift) const
Calculates an average of several traces.
void AddRec (const Recording &toAdd)
Add a Recording at the end of this Recording.
stf::Table CurAsTable () const
Put the current trace into a text table.
stf::Table CurResultsTable ()
Put the current measurement results into a text table.
const XZoom & GetXZoom ()
Returns the current zoom settings for this channel (read-only).
XZoom & GetXZoomW ()
Returns the current zoom settings for this channel (read & write).
Channel & operator[] (std::size_t at)
Unchecked channel access (read and write)
const Channel & operator[] (std::size_t at) const
Unchecked channel access (read-only)
Detailed Description
Represents the data within a file.
Contains an array of channels that can be accessed either via at() (range-checked, will throw an exception if out of range) or the []-operator (range unchecked). Moreover all the metadata such as time, date, samling rate and comments are stored here.
Constructor & Destructor Documentation
Recording::Recording (const Channel & c_Channel) [explicit]
Constructor.
Parameters:
c_Channel The Channel from which to construct a new Recording.
Recording::Recording (const std::vector< Channel > & ChannelList) [explicit]
Constructor.
Parameters:
ChannelList A vector of channels from which to construct a new Recording.
Recording::Recording (std::size_t c_n_channels, std::size_t c_n_sections = 0, std::size_t c_n_points = 0) [explicit]
Constructor.
Setting the number of channels and sections at construction time will avoid unnecessary memory re-allocations.
Parameters:
c_n_channels The number of channels.
c_n_sections The number of sections.
c_n_points The number of sampling points per section.
Member Function Documentation
void Recording::AddRec (const Recording & toAdd)
Add a Recording at the end of this Recording.
Parameters:
toAdd The Recording to be added.
const Channel& Recording::at (std::size_t n_c) const
Range-checked access to a channel (read-only).
Will throw std::out_of_range if out of range.
Parameters:
n_c The index of the channel.
Returns:
The channel at index n_c.
Channel& Recording::at (std::size_t n_c)
Range-checked access to a channel (read and write).
Will throw std::out_of_range if out of range.
Parameters:
n_c The index of the channel.
Returns:
The channel at index n_c.
void Recording::CopyAttributes (const Recording & c_Recording)
Copy descriptive attributes from another Recording to this Recording.
This will copy the file and global section decription, the scaling, time, date, comment and global y units strings and the x-scale.
Parameters:
c_Recording The Recording from which to copy the attributes.
void Recording::CopyCursors (const Recording & c_Recording)
Copies the cursor positions from another Recording to this Recording.
This will copy the crosshair, base, peak and fit cursors positions as well as the number of points for peak averaging from another Recording and correct the new values if they are out of range. The latency cursors will not be copied.
Parameters:
c_Recording The Recording from which to copy the cursor positions.
const Section& Recording::cur () const [inline]
Retrieves the currently accessed section in the active channel (read-only)
Returns:
The currently accessed section in the active channel.
Section& Recording::cur () [inline]
Retrieves the currently accessed section in the active channel (read and write)
Returns:
The currently accessed section in the active channel.
const std::vector<Channel>& Recording::get () const [inline]
Retrieves the channels (read-only).
Returns:
A vector containing the channels.
std::vector<Channel>& Recording::get () [inline]
Retrieves the channels (read and write).
Returns:
A vector containing the channels.
double Recording::GetAPBase () const [inline]
Retrieves the baseline in the second channel.
Returns:
The baseline value in the second channel.
double Recording::GetAPMaxRiseT () const [inline]
Retrieves the time point of the maximal slope of the rising phase in the second channel.
This time point is needed as a reference for the latency calculation and for aligned averages.
Returns:
The time point at which the maximal slope of the rising phase is reached in the second channel, expressed in units of data points..
double Recording::GetAPMaxT () const [inline]
Retrieves the time point of the peak in the second channel.
Returns:
The time point at which the peak is found in the second channel, expressed in units of data points.
double Recording::GetAPT50LeftReal () const [inline]
Retrieves the time point at which 50% of the max. amplitude have been reached from the left of the peak in the inactive channel.
Returns:
The time point at which 50% of the maximal amplitude have been reached from the left of the peak in the inactive channel, expressed in units of data points.
double Recording::GetBase () const [inline]
Retrieves the baseline.
Returns:
The baseline value.
References stf::base().
std::size_t Recording::GetBaseBeg () const [inline]
Retrieves the position of the left baseline cursor.
Returns:
The index of the left baseline cursor within the current section.
std::size_t Recording::GetBaseEnd () const [inline]
Retrieves the position of the right baseline cursor.
Returns:
The index of the left baseline cursor within the current section.
double Recording::GetBaseSD () const [inline]
Retrieves the standard deviation of the baseline.
Returns:
The standard deviation of the baseline.
std::size_t Recording::GetChannelSize (std::size_t n_channel) const
Retrieves the number of sections in a channel.
Parameters:
n_channel The index of the channel (range-checked).
Returns:
The number of sections in n_channel.
const std::string& Recording::GetComment () const [inline]
Retrieves a comment string.
Returns:
A string containing a comment.
std::size_t Recording::GetCurCh () const [inline]
Retrieves the index of the current channel.
Returns:
The index of the current channel.
std::size_t Recording::GetCurSec () const [inline]
Retrieves the index of the current section.
Returns:
The index of the current section.
const std::string& Recording::GetDate () const [inline]
Retrieves the date of recording as a string.
Returns:
A string containing the date of recording.
stf::direction Recording::GetDirection () const [inline]
Retrieves the direction of peak calculations.
Returns:
The current direction of peak calculations.
const std::string& Recording::GetFileDescription () const [inline]
Retrieves the file description.
Returns:
The file description.
std::size_t Recording::GetFitBeg () const [inline]
Retrieves the position of the left fitting cursor.
Returns:
The index of the left fitting cursor within the current section.
std::size_t Recording::GetFitEnd () const [inline]
Retrieves the position of the right fitting cursor.
Returns:
The index of the right fitting cursor within the current section.
bool Recording::GetFromBase () const [inline]
Indicates whether to use the baseline as a reference for AP kinetics.
Returns:
true if the baseline should be used, false if the threshold should be used.
const std::string& Recording::GetGlobalSectionDescription () const [inline]
Retrieves the common section description.
Returns:
The common section description.
double Recording::GetHalfDuration () const [inline]
Retrieves the full width at half-maximal amplitude ("half duration").
Returns:
The difference between GetT50RightReal() and GetT50LeftReal(), expressed in units of data points.
double Recording::GetLatency () const [inline]
Retrieves the latency.
Returns:
The latency, expressed in units of data points.
double Recording::GetLatencyBeg () const [inline]
Retrieves the position of the left latency cursor.
Returns:
The index of the left latency cursor within the current section. Note that by contrast to the other cursors, this is a double because the latency cursor may be set to an interpolated position between two data points.
double Recording::GetLatencyEnd () const [inline]
Retrieves the position of the right latency cursor.
Returns:
The interpolated index of the right latency cursor within the current section. Note that by contrast to the other cursors, this is a double because the latency cursor may be set to an interpolated position between two data points.
stf::latency_mode Recording::GetLatencyEndMode () const [inline]
Retrieves the mode of the latency end cursor.
Returns:
The current mode of the latency end cursor.
stf::latency_mode Recording::GetLatencyStartMode () const [inline]
Retrieves the mode of the latency start cursor.
Returns:
The current mode of the latency start cursor..
stf::latency_window_mode Recording::GetLatencyWindowMode () const [inline]
Retrieves the mode of the latency window.
Returns:
The current mode of the latency window.
double Recording::GetMaxDecay () const [inline]
Retrieves the maximal slope of the decaying phase.
Returns:
The maximal slope of rise.
References stf::maxDecay().
double Recording::GetMaxDecayT () const [inline]
Retrieves the time point of the maximal slope during the decaying phase.
Returns:
The time point of the maximal slope during the decaying phase, expressed in units of data points.
double Recording::GetMaxDecayY () const [inline]
Retrieves the y-value at the time point of the maximal slope during the decaying phase.
Returns:
The y-value at the time point of the maximal slope during the decaying phase.
double Recording::GetMaxRise () const [inline]
Retrieves the maximal slope of the rising phase.
Returns:
The maximal slope during the rising phase.
References stf::maxRise().
double Recording::GetMaxRiseT () const [inline]
Retrieves the time point of the maximal slope during the rising phase.
Returns:
The time point of the maximal slope during the rising phase, expressed in units of data points.
double Recording::GetMaxRiseY () const [inline]
Retrieves the y-value at the time point of the maximal slope during the rising phase.
Returns:
The y-value at the time point of the maximal slope during the rising phase.
double Recording::GetMaxT () const [inline]
Retrieves the time point at which the peak is found.
Returns:
The time point at which the peak is found, expressed in units of data points.
std::size_t Recording::GetMeasCursor () const [inline]
Retrieves the position of the measurement cursor (crosshair).
Returns:
The index of the measurement cursor within the current section.
double Recording::GetMeasValue ()
Retrieves the y-value at the measurement cursor (crosshair). Will update measCursor if out of range.
Returns:
The y-value at the measurement cursor.
double Recording::GetPeak () const [inline]
Retrieves the peak value.
Returns:
The peak value.
References stf::peak().
std::size_t Recording::GetPeakBeg () const [inline]
Retrieves the position of the left peak cursor.
Returns:
The index of the left peak cursor within the current section.
std::size_t Recording::GetPeakEnd () const [inline]
Retrieves the position of the right peak cursor.
Returns:
The index of the right peak cursor within the current section.
int Recording::GetPM () const [inline]
Retrieves the number of points used for averaging during peak calculation.
Returns:
The number of points to be used.
double Recording::GetPSlope () const [inline]
Retrieves the value of the Slope.
Returns:
slope value in y-units/x-units.
double Recording::GetRT2080 () const [inline]
Retrieves the 20 to 80% rise time.
Returns:
The difference between GetT80Real() and GetT20Real(), expressed in units o data points.
const std::string& Recording::GetScaling () const [inline]
Retrieves the scaling as a string.
Returns:
A string containing the description.
std::size_t Recording::GetSecCh () const [inline]
Retrieves the index of the second channel.
Returns:
The index of the second channel.
const Vector_double& Recording::GetSelectBase () const [inline]
Retrieves the stored baseline values of the selected sections (read-only).
Returns:
A vector containing the stored baseline values of the selected sections.
Vector_double& Recording::GetSelectBaseW () [inline]
Retrieves the stored baseline values of the selected sections (read and write).
Returns:
A vector containing the stored baseline values of the selected sections.
const std::vector<std::size_t>& Recording::GetSelectedSections () const [inline]
Retrieves the indices of the selected sections (read-only).
Returns:
A vector containing the indices of the selected sections.
std::vector<std::size_t>& Recording::GetSelectedSectionsW () [inline]
Retrieves the indices of the selected sections (read and write).
Returns:
A vector containing the indices of the selected sections.
double Recording::GetSlopeForThreshold () const [inline]
Returns the slope for threshold detection.
Returns:
The slope value for threshold detection.
double Recording::GetSlopeRatio () const [inline]
Retrieves ratio of the maximal slopes during the rising and decaying phase.
Returns:
The ratio of GetMaxRise() and GetMaxDecay().
double Recording::GetSR () const [inline]
Retrieves the sampling rate (1 / x-scale)
Returns:
The sampling rate.
double Recording::GetT20Real () const [inline]
Retrieves the time point at which 20% of the maximal amplitude have been reached.
Returns:
The time point at which 20% of the maximal amplitude have been reached, expressed in units of data points.
double Recording::GetT50LeftReal () const [inline]
Retrieves the time point at which 50% of the maximal amplitude have been reached from the left of the peak.
Returns:
The time point at which 50% of the maximal amplitude have been reached from the left of the peak, expressed in units of data points.
double Recording::GetT50RightReal () const [inline]
Retrieves the time point at which 50% of the maximal amplitude have been reached from the right of the peak.
Returns:
The time point at which 50% of the maximal amplitude have been reached from the right of the peak, expressed in units of data points.
double Recording::GetT50Y () const [inline]
Retrieves the y value at 50% of the maximal amplitude.
Returns:
The y value at 50% of the maximal amplitude.
double Recording::GetT80Real () const [inline]
Retrieves the time point at which 80% of the maximal amplitude have been reached.
Returns:
The time point at which 80% of the maximal amplitude have been reached, expressed in units of data points.
double Recording::GetThreshold () const [inline]
Retrieves the value at which the threshold slope is crossed.
Returns:
The standard deviation of the baseline.
References stf::threshold().
double Recording::GetThrT () const [inline]
Retrieves the time point at which the threshold slope is crossed.
Returns:
The time point at which the threshold slope is crossed, or a negative value if the threshold is not attained.
const std::string& Recording::GetTime () const [inline]
Retrieves the time of recording as a string.
Returns:
A string containing the time of recording.
bool Recording::GetViewBaseline () const [inline]
Indicates whether the baseline value should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewBaseSD () const [inline]
Indicates whether the baseline's standard deviation should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewCrosshair () const [inline]
Indicates whether the measurement cursor (crosshair) value should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewCursors () const [inline]
Indicates whether two additional rows showing the positions of start and end cursors should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewLatency () const [inline]
Indicates whether the latency should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewPeakBase () const [inline]
Indicates whether the peak value (measured from baseline) should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewPeakThreshold () const [inline]
Indicates whether the peak value (measured from threshold) should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewPeakZero () const [inline]
Indicates whether the peak value (measured from zero) should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewRD () const [inline]
Indicates whether the ratio of the maximal slopes during rise and decay should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewRT2080 () const [inline]
Indicates whether the 20 to 80% rise time should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewSlopeDecay () const [inline]
Indicates whether the maximal slope during the decaying phase should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewSlopeRise () const [inline]
Indicates whether the maximal slope during the rising phase should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewT50 () const [inline]
Indicates whether the half duration should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
bool Recording::GetViewThreshold () const [inline]
Indicates whether the threshold should be shown in the results table.
Returns:
true if it should be shown, false otherwise.
double Recording::GetXScale () const [inline]
Retrieves the x scaling (sampling interval).
Returns:
The x scaling.
const std::string& Recording::GetXUnits () const [inline]
Retrieves the x units.
Returns:
The x units. Currently hard-coded to be "ms".
const XZoom& Recording::GetXZoom () [inline]
Returns the current zoom settings for this channel (read-only).
Returns:
The current zoom settings.
XZoom& Recording::GetXZoomW () [inline]
Returns the current zoom settings for this channel (read & write).
Returns:
The current zoom settings.
void Recording::InsertChannel (Channel & c_Channel, std::size_t pos)
Insert a Channel at a given position.
Will throw std::out_of_range if range check fails.
Parameters:
c_Channel The Channel to be inserted.
pos The position at which to insert the channel (0-based).
void Recording::MakeAverage (Section & AverageReturn, Section & SigReturn, std::size_t channel, const std::vector< std::size_t > & section_index, bool isSig, const std::vector< int > & shift) const
Calculates an average of several traces.
Parameters:
AverageReturn The average will be returned in this variable by passing a reference. AverageReturn has to have the correct size upon entering this function already, it won't be resized.
SigReturn The standard deviation will be returned in this variable by passing a reference if isSig == true. SigReturn has to have the correct size upon entering this function already, it won't be resized.
channel The index of the channel to be used.
section_index A vector containing the indices of the sections to be used for the average.
isSig Set to true if the standard deviation should be calculated as well.
shift A vector indicating by how many data points each section should be shifted before averaging.
void Recording::Measure ()
Measure everything using functions defined in measlib.h.
This will measure the baseline, peak values, 20 to 80% rise time, half duration, maximal slopes during rise and decay, the ratio of these slopes and the latency.
const Channel& Recording::operator[] (std::size_t at) const [inline]
Unchecked channel access (read-only)
Use at() for range-checked access.
Parameters:
at The channel index.
Channel& Recording::operator[] (std::size_t at) [inline]
Unchecked channel access (read and write)
Use at() for range-checked access.
Parameters:
at The channel index.
void Recording::resize (std::size_t c_n_channels)
Resize the Recording to a new number of channels.
Resizes both the channel and the global y units arrays.
Parameters:
c_n_channels The new number of channels.
const Section& Recording::sec () const [inline]
Retrieves the currently accessed section in the second (inactive) channel (read-only)
Returns:
The currently accessed section in the second (inactive) channel.
void Recording::SelectTrace (std::size_t sectionToSelect)
Selects a section.
Parameters:
sectionToSelect The index of the section to be selected.
void Recording::SetBaseBeg (int value)
Sets the position of the left baseline cursor.
Parameters:
value The index of the left baseline cursor within the current section.
void Recording::SetBaseEnd (int value)
Sets the position of the right baseline cursor.
Parameters:
value The index of the left baseline cursor within the current section.
void Recording::SetComment (const std::string & value) [inline]
Sets a comment string.
Parameters:
value A string containing a comment.
void Recording::SetCurCh (std::size_t value)
Sets the index of the current channel.
Parameters:
value The index of the current channel.
void Recording::SetCurSec (std::size_t value)
Sets the index of the current section.
Parameters:
value The index of the current section.
void Recording::SetDate (const std::string & value) [inline]
Sets the date of recording as a string.
Parameters:
value A string containing the date of recording.
void Recording::SetDirection (stf::direction value) [inline]
Sets the direction of peak calculations.
Parameters:
value The new direction of peak calculations.
void Recording::SetFileDescription (const std::string & value) [inline]
Sets the file description.
Parameters:
value The file description.
void Recording::SetFitBeg (int value)
Sets the position of the left fitting cursor.
Parameters:
value The index of the left fitting cursor within the current section.
void Recording::SetFitEnd (int value)
Sets the position of the right fitting cursor.
Parameters:
value The index of the right fitting cursor within the current section.
void Recording::SetFromBase (bool frombase) [inline]
Sets the reference for AP kinetics measurements.
Parameters:
frombase true if the baseline should be used, false if the threshold should be used.
void Recording::SetGlobalSectionDescription (const std::string & value) [inline]
Sets the common section description.
Parameters:
value The common section description.
void Recording::SetGlobalYUnits (std::size_t n_channel, const std::string & value)
Sets the y units for a channel.
Parameters:
n_channel The channel index for which to set the units.
value A string containing the y units.
void Recording::SetLatency (double value) [inline]
Sets the latency.
Parameters:
value The latency, expressed in units of data points.
void Recording::SetLatencyBeg (double value)
Sets the position of the left latency cursor.
Parameters:
value The index of the left latency cursor within the current section. Note that by contrast to the other cursors, this is a double because the latency cursor may be set to an interpolated position between two data points.
void Recording::SetLatencyEnd (double value)
Sets the position of the right latency cursor.
Parameters:
value The index of the right latency cursor within the current section. Note that by contrast to the other cursors, this is a double because the latency cursor may be set to an interpolated position between two data points.
void Recording::SetLatencyEndMode (int value)
Sets the mode of the latency end cursor.
Parameters:
value The new mode of the latency end cursor..
void Recording::SetLatencyEndMode (stf::latency_mode value) [inline]
Sets the mode of the latency end cursor.
Parameters:
value The new mode of the latency end cursor..
void Recording::SetLatencyStartMode (stf::latency_mode value) [inline]
Sets the mode of the latency start cursor.
Parameters:
value The new mode of the latency start cursor..
void Recording::SetLatencyStartMode (int value)
Sets the mode of the latency start cursor.
Parameters:
value The new mode of the latency start cursor..
void Recording::SetLatencyWindowMode (int value)
Sets the mode of the latency end cursor.
Parameters:
value The new mode of the latency end cursor..
void Recording::SetLatencyWindowMode (stf::latency_window_mode value) [inline]
Sets the mode of the latency end cursor.
Parameters:
value The new mode of the latency end cursor..
void Recording::SetMeasCursor (int value)
Sets the position of the measurement cursor (crosshair).
Parameters:
value The index of the measurement cursor within the current section.
void Recording::SetPeakBeg (int value)
Sets the position of the left peak cursor.
Parameters:
value The index of the left peak cursor within the current section.
void Recording::SetPeakEnd (int value)
Sets the position of the right peak cursor.
Parameters:
value The index of the right peak cursor within the current section.
void Recording::SetPM (int value) [inline]
Sets the number of points used for averaging during peak calculation.
Parameters:
value The number of points to be used.
void Recording::SetScaling (const std::string & value) [inline]
Sets the scaling as a string.
Parameters:
value A string containing the description.
void Recording::SetSecCh (std::size_t value)
Sets the index of the second channel.
Parameters:
value The index of the second channel.
void Recording::SetSlopeForThreshold (double value) [inline]
Sets the slope where the baseline should be set.
Parameters:
value The slope value where the baseline shoudl be set.
void Recording::SetTime (const std::string & value) [inline]
Sets the time of recording as a string.
Parameters:
value A string containing the time of recording.
void Recording::SetViewBaseline (bool value) [inline]
Determines whether the baseline value should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewBaseSD (bool value) [inline]
Determines whether the baseline's standard deviation should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewCrosshair (bool value) [inline]
Determines whether the measurement cursor (crosshair) value should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewCursors (bool value) [inline]
Determines whether two additional rows showing the positions of start and end cursors should be shown in the results table.
Parameters:
value Set to true if they should be shown, false otherwise.
void Recording::SetViewLatency (bool value) [inline]
Determines whether the latency should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewPeakBase (bool value) [inline]
Determines whether the peak value (measured from baseline) should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewPeakThreshold (bool value) [inline]
Determines whether the peak value (measured from threshold) should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewPeakZero (bool value) [inline]
Determines whether the peak value (measured from zero) should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewRD (bool value) [inline]
Determines whether the ratio of the maximal slopes during rise and decay should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewRT2080 (bool value) [inline]
Determines whether the 20 to 80% rise time should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewSlopeDecay (bool value) [inline]
Determines whether the maximal slope during the decaying phase should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewSlopeRise (bool value) [inline]
Determines whether the maximal slope during the rising phase should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewT50 (bool value) [inline]
Determines whether the half duration should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetViewThreshold (bool value) [inline]
Determines whether the threshold should be shown in the results table.
Parameters:
value Set to true if it should be shown, false otherwise.
void Recording::SetXScale (double value)
Sets the x scaling.
Note that setting the global x-scale will set it for all sections
Parameters:
value The x scaling.
void Recording::SetXUnits (const std::string & value) [inline]
Sets the x units.
Parameters:
value A string containing the x units.
std::size_t Recording::size () const [inline]
Retrieves the size of the channel array.
Returns:
The size of the channel array.
bool Recording::UnselectTrace (std::size_t sectionToUnselect)
Unselects a section if it was selected before.
Parameters:
sectionToUnselect The index of the section to be unselected.
Returns:
true if the section was previously selected, false otherwise.
The documentation for this class was generated from the following file:
src/core/recording.h